batch_size: 64
test_batch_size: 100
lr: 0.00001
momentum: 0.9
decay: 0.0005
epochs: 350
save_on_epochs: []
optimizer: Adam
log_interval: 10


scheduler: True

#resumed_model: model_image_Aug.15_11.40.44/model_last.pt.tar

#resumed_model: model_image_cifar_Oct.01_11.37.45/model_last.pt.tar

#resumed_model: ../../bd_proj/smoothing/models/cifar10/resnet110/noise_0.25/checkpoint.pth.tar

#resumed_model: model_image_Aug.31_17.16.10/model_last.pt.tar
#resumed_model: model_image_Sep.11_14.56.21/model_last.pt.tar # backdoored


data: imagenet

poisoning_proportion: 1.1
poison_number: 8
backdoor: True
alpha: 0.95
scale_threshold: 0.1

normalize: eq

save_model: True
log: True
tb: False

random: True
gan: False
defense: True
transform_train: True

nc: False
smoothing: False

losses:
  - backdoor
  - normal
#  - nc_adv
#  - ewc
  - latent
#  - latent_fixed

losses_scales:
  backdoor: 0.1
  normal: 1.0
  latent: 1.0
#  latent_fixed: 0.2

#poison_images_test:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588
#
#poison_images:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588