batch_size: 128
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
epochs: 90
save_on_epochs: [10, 50, 58, 59, 60]
optimizer: SGD
log_interval: 100


scheduler: True

#resumed_model: model_image_Aug.15_11.40.44/model_last.pt.tar

#resumed_model: model_image_cifar_Oct.01_11.37.45/model_last.pt.tar

#resumed_model: ../../bd_proj/smoothing/models/cifar10/resnet110/noise_0.25/checkpoint.pth.tar

#resumed_model: model_image_Aug.31_17.16.10/model_last.pt.tar
#resumed_model: model_image_Sep.11_14.56.21/model_last.pt.tar # backdoored

#resumed_model: model_image_imagenet_Apr.09_15.54.30/model_last.pt.tar

data: imagenet

poisoning_proportion: 10.5
poison_number: 8
single_pixel: True
backdoor: True
alpha: 0.95
scale_threshold: 0.01

normalize: loss+

pretrained: False

save_model: True
log: True
tb: True

random_seed: 8
gan: False
defense: True
transform_train: True


smoothing: False

timing: False
alternating_attack: 0.1
memory: False
disable_dropout: False
subbatch: 64
slow_start: False

new_nc_evasion: False

losses:
  - backdoor
  - normal
#  - nc_adv
#  - ewc
#  - latent
#  - latent_fixed

losses_scales:
  backdoor: 0.1
  normal: 1
  latent: 0.1
  nc_adv: 0.1
  latent_fixed: 0.2

#poison_images_test:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588
#
#poison_images:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588